name       : perl-extutils-libbuilder
version    : 0.08
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/A/AM/AMBS/ExtUtils-LibBuilder-0.08.tar.gz : c51171e06de53039f0bca1d97a6471ec37941ff59e8a3d1cb170ebdd2573b5d2
license    : Artistic-2.0
component  : programming.perl
summary    : ExtUtils::LibBuilder - A tool to build C libraries.
description: |
    ExtUtils::LibBuilder - A tool to build C libraries.
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
